import tseslint from 'typescript-eslint';
import noFloatMoney from './eslint-rules/no-float-money.js';
import noClientClock from './eslint-rules/no-client-clock.js';

const cse = { rules: { 'no-float-money': noFloatMoney, 'no-client-clock': noClientClock } };

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'drizzle/**',
      'coverage/**',
      'docs/**',
      // Deliberately broken files that PROVE the custom rules fire. The test
      // lints them explicitly with --no-ignore; the ordinary run must not.
      'tests/fixtures/**',
      // Generated by `next build`; not ours to lint.
      'next-env.d.ts',
    ],
  },
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { cse },
    rules: {
      'cse/no-float-money': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  {
    // Invariant 5 applies where the server decides what time it is.
    files: ['src/server/services/**/*.ts', 'src/server/jobs/**/*.ts', 'src/server/agent/**/*.ts'],
    rules: { 'cse/no-client-clock': 'error' },
  },
  {
    files: ['tests/**/*.ts'],
    rules: { 'cse/no-client-clock': 'off' },
  },
);
