/**
 * Die EINGEFRORENE Warteliste: Katalogschlüssel, die heute noch kein Code prüft.
 *
 * Der grösste Teil des Katalogs gehört zu Modulen, die in Phase 4 bis 9
 * landen. Die Prüfung abzuschalten wäre das eine; sie einzufrieren heisst:
 * die Menge der unbenutzten Schlüssel darf nur SCHRUMPFEN. Ein neu erfundener
 * Schlüssel, den niemand prüft, steht nicht darauf und bricht den Build —
 * genau der Fall, den K-19 meint.
 *
 * Beim Landen eines Moduls werden seine Zeilen hier gestrichen. Ergänzt wird
 * nur mit einer Begründung im Pull Request.
 *
 * 198 von 242 Schlüsseln.
 *
 * Die Zahl stieg mit PR 17, weil der Extraktor bis dahin jede §12-Zeile
 * übersprang, die ZWEI Schlüssel nennt (`crm.lesen` / `crm.schreiben`). 19
 * Schlüssel fehlten dadurch im Katalog — und `app.hat_recht` antwortet auf
 * einen fehlenden Schlüssel mit `false`. Vier davon benutzt PR 17 sofort
 * (`crm.*`, `formular.*`); die übrigen 15 gehören zu Modulen späterer Phasen
 * und stehen deshalb hier.
 *
 * PR 19 fügt VIER hinzu, und keiner davon ist erfunden: §12.9 trägt die
 * `agent`-, `wissen`- und `freigabe`-Zeilen nach, die §14.2 in Prosa
 * deklariert und die Matrix nie führte. Zwölf der sechzehn benennt die
 * Seitenkarte sofort, also gelten sie als benutzt. Die übrigen vier —
 * `agent.autonomie_setzen`, `freigabe.alle_lesen`, `wissen.lesen`,
 * `wissen.vertraulich_lesen` — benennt keine ROUTE, sondern eine POLICY
 * eines Datenmodell-Dokuments (Phase 8). Sie stehen deshalb hier und nicht
 * im Code.
 */
export const NOCH_UNBENUTZT: readonly string[] = [
  "abrechnung.freistellung_pflegen",
  "abrechnung.lesen",
  "abrechnung.schreiben",
  "agent.autonomie_setzen",
  "angebot.annahme_erfassen",
  "angebot.preis_freigeben",
  "angebot.schreiben",
  "angebot.versenden",
  "aufgabe.lesen",
  "aufgabe.schreiben",
  "aufgabe.zuweisen",
  "auftrag.abschliessen",
  "auftrag.schreiben",
  "bau.aufmass_erfassen",
  "bau.aufmass_freigeben",
  "bau.behinderung_erstellen",
  "bau.lesen",
  "bau.nachtrag_anmelden",
  "bau.nachtrag_einreichen",
  "bau.preis_lesen",
  "bau.schreiben",
  "bericht.exportieren",
  "bericht.lesen",
  "buchhaltung.exportieren",
  "buchhaltung.festschreiben",
  "buchhaltung.lesen",
  "buchhaltung.schreiben",
  "buchhaltung_konfiguration.lesen",
  "buchhaltung_konfiguration.verwalten",
  "crm.exportieren",
  "crm.kommunikation_versenden",
  "crm.rechtsgrundlage_lesen",
  "crm.rechtsgrundlage_setzen",
  "crm_entgelt.lesen",
  "datenschutz.auskunft_erstellen",
  "datenschutz.berichtigung_bearbeiten",
  "datenschutz.loeschung_pruefen",
  "dienstanweisung.lesen",
  "dienstanweisung.schreiben",
  "dienstplan.arbzg_lesen",
  "dienstplan.arbzg_pruefen",
  "dienstplan.arbzg_uebersteuern",
  "dienstplan.konflikt_quittieren",
  "dienstplan.schreiben",
  "dienstplan.veroeffentlichen",
  "dokument.archivieren",
  "dokument.aufbewahrung_verwalten",
  "dokument.buendel_exportieren",
  "dokument.kunde_freigeben",
  "eingang.freigeben",
  "eingang.lesen",
  "eingang.schreiben",
  "finanzen.entwurf_verwerfen",
  "finanzen.festschreiben",
  "finanzen.herunterladen",
  "finanzen.schreiben",
  "finanzen.steuerfall_uebersteuern",
  "finanzen.stornieren",
  "freigabe.alle_lesen",
  "gruppe.abrechnung.lesen",
  "gruppe.agent.lesen",
  "gruppe.angebot.lesen",
  "gruppe.aufgabe.lesen",
  "gruppe.auftrag.lesen",
  "gruppe.bau.lesen",
  "gruppe.bericht.lesen",
  "gruppe.buchhaltung.lesen",
  "gruppe.buchhaltung_konfiguration.lesen",
  "gruppe.crm.lesen",
  "gruppe.crm_entgelt.lesen",
  "gruppe.datenschutz.lesen",
  "gruppe.dienstanweisung.lesen",
  "gruppe.dienstplan.arbzg_lesen",
  "gruppe.dienstplan.lesen",
  "gruppe.eingang.lesen",
  "gruppe.finanzen.lesen",
  "gruppe.formular.lesen",
  "gruppe.kalender.lesen",
  "gruppe.kalkulation.lesen",
  "gruppe.katalog.lesen",
  "gruppe.mahnung.lesen",
  "gruppe.nachweis.lesen",
  "gruppe.nummernkreis.lesen",
  "gruppe.objekt.lesen",
  "gruppe.objekt_import.lesen",
  "gruppe.oeffentlich.lesen",
  "gruppe.personal.lesen",
  "gruppe.qualitaet.lesen",
  "gruppe.radar.lesen",
  "gruppe.recruiting.lesen",
  "gruppe.referenz.lesen",
  "gruppe.reinigung.lesen",
  "gruppe.schluessel.lesen",
  "gruppe.security.lesen",
  "gruppe.social.lesen",
  "gruppe.stammdaten.lesen",
  "gruppe.system.audit_lesen",
  "gruppe.system.lesen",
  "gruppe.vergabe.lesen",
  "gruppe.versand.lesen",
  "gruppe.wachbuch.lesen",
  "gruppe.wissen.lesen",
  "gruppe.zahlung.lesen",
  "gruppe.zeit.lesen",
  "kalender.lesen",
  "kalender.schreiben",
  "kalkulation.lesen",
  "kalkulation.schreiben",
  "katalog.lesen",
  "katalog.schreiben",
  "mahnung.freigeben",
  "mahnung.lesen",
  "mahnung.schreiben",
  "nachweis.lesen",
  "nachweis.preis_lesen",
  "nachweis.schreiben",
  "nummernkreis.lesen",
  "objekt.schreiben",
  "objekt_import.lesen",
  "objekt_import.schreiben",
  "oeffentlich.lesen",
  "personal.aendern",
  "personal.anstellung_beenden",
  "personal.bewacher_verwalten",
  "personal.entgelt_lesen",
  "personal.entgelt_schreiben",
  "personal.erstattung_lesen",
  "personal.erstellen",
  "personal.nachweis_lesen",
  "personal.nachweis_verwalten",
  "personal.schreiben",
  "personal.stammdaten_lesen",
  "personal.zugang_verwalten",
  "personal.zusammenfuehren",
  "qualitaet.lesen",
  "qualitaet.schreiben",
  "radar.lesen",
  "radar.plattform_verwalten",
  "radar.profil_schreiben",
  "radar.status_setzen",
  "recruiting.bewerbung_bewerten",
  "recruiting.bewerbung_lesen",
  "recruiting.daten_loeschen",
  "recruiting.entscheiden",
  "recruiting.stelle_lesen",
  "recruiting.stelle_schreiben",
  "recruiting.stelle_veroeffentlichen",
  "referenz.veroeffentlichen",
  "reinigung.lesen",
  "reinigung.schreiben",
  "schluessel.lesen",
  "schluessel.schreiben",
  "security.lesen",
  "security.schreiben",
  "social.freigeben",
  "social.kanal_verbinden",
  "social.lesen",
  "social.planen",
  "social.schreiben",
  "stammdaten.verwalten",
  "system.audit_exportieren",
  "system.audit_lesen",
  "system.einstellung_verwalten",
  "system.feed_token_widerrufen",
  "system.identitaet_verwalten",
  "system.mandant_lesen",
  "system.mandant_verwalten",
  "system.module_zuweisen",
  "system.protokoll_lesen",
  "system.referenzdaten_verwalten",
  "system.rolle_lesen",
  "system.sitzung_lesen",
  "system.sitzung_widerrufen",
  "system.zwei_faktor_zuruecksetzen",
  "vergabe.einreichung_erfassen",
  "vergabe.lesen",
  "vergabe.schreiben",
  "wachbuch.lesen",
  "wachbuch.schreiben",
  "wissen.lesen",
  "wissen.vertraulich_lesen",
  "zahlung.lesen",
  "zahlung.schreiben",
  "zeit.abrechnung_freigeben",
  "zeit.abwesenheit_genehmigen",
  "zeit.abwesenheit_grund_lesen",
  "zeit.abwesenheit_lesen",
  "zeit.abwesenheit_melden",
  "zeit.antrag_entscheiden",
  "zeit.checkin_verwalten",
  "zeit.einwand_entscheiden",
  "zeit.exportieren",
  "zeit.konto_abschliessen",
  "zeit.konto_korrigieren",
  "zeit.konto_lesen",
  "zeit.korrigieren",
  "zeit.nacherfassung_pruefen",
  "zeit.schreiben",
];
